### ISSUE TITLE
Specify on/off time parameters?

### ISSUE THREAD

**Issue by john2691** [isalkind/homebridge-away-mode#1]
Is there a way to specify when the lights should stop turning on randomly? For the sake of realism, it would be great to not have lights turning on all night at random intervals.

**Comment by isalkind** [comment]
Think of it as a controllable light switch. You add an automation to turn it on when you want (dusk, 7pm, etc). You add an automation to turn it off when you want (dawn, 10pm, etc).

I typically set this up to turn on 15 minutes before sunset, and turn off at 10pm.

**Comment by john2691** [comment]
Of course, brilliant. Thank you!
