### ISSUE TITLE
Trigger not activated if the sum of  planned off-time + planned on-time is past the set "end" time 

### ISSUE THREAD

**Issue by Jodifoto** [isalkind/homebridge-away-mode#10]
The Motion-Trigger is not activated if the sum of planned off-time + planned on-time is past the set "end"-time for that trigger.
I use a very big "minOnTime"-time to take care that the trigger will only pulled ONCE between "start" & "end" time.
The   "minOffTime" and "maxOffTime" are within the "start" & "end" time so that a random delay will occur before the Motion-Trigger is activated ONLY ONCE.
Please allow the Motion-Trigger to activate if the ON-time is before the "end" time.
Thanks.

**Comment by isalkind** [comment]
What is the actual behavior you're looking for? I might rather add functionality than try to "fix" the current functionality to match the behavior you're trying to achieve.

**Comment by Jodifoto** [comment]
Hi isalkind. The actual behaviour is that the "Motion Sensor" should only be activated ONCE within the same defined time-period in the config.json ... for example  "start": "sunset",  "end": "11:45". 
This is needed to close roller-shutters BUT I want to be able to open a roller-shutter again manually if I am at home and I need this ... without having Home-Kit closing it again ..., 
If you like to add a functionality, it could be for example an extra parameter "maxNumActivations" being the maximun Number of Activations of the "Motion Sensor" within the same defined time-period in the config.json ... for example  "start": "sunset",  "end": "11:45". 
Then it is not restricted to only one activation of the "Motion Sensor" within the same defined time-period.
Thanks.

**Comment by isalkind** [comment]
This should be doable. Give me a couple of days to code/test.

**Comment by isalkind** [comment]
Released version 1.6 to address this issue. Added 'maxActivations' on 'Active Periods'. It can be set globally or per-sensor.

Please let me know if this meets your needs.

**Comment by Jodifoto** [comment]
@ isallind, thans for the quick programming. The solution looks perfect to me !
Unfortunately I'll not be at home for the next 2 weeks ... so testing is difficult ... I'll do it as soon as I can!

**Comment by Jodifoto** [comment]
@isalkind, After testing I can confirm that the new feature works well. Thanks for your efforts !! ... and your very nice and useful program ! 
(sorry for the delay due to travel ...)

**Comment by isalkind** [comment]
Glad it works for you.
