### ISSUE TITLE
activeTimes vs. activeTimesForSensor

### ISSUE THREAD

**Issue by PatriceRobert** [isalkind/homebridge-away-mode#15]
Dear all,

When configuring the latest plugin release, the doc is showing up `activeTimes` as an option but when configuring it, it was not working and was executing:
```
    "activeSeconds": [
      {
        "start": 0,
        "end": 86340
      }
```

In the logs, we can also see an `activeTimesForSensor` option, I configured this one instead of `activeTimes` and it now looks much better:

```
    "activeTimesForSensor": [
      {
        "start": "sunset",
        "end": "sunrise",
        "absolute": true
      }
    ],
    "offset": {
      "sunrise": -30,
      "sunset": 19
    },
    "id": 0,
    "activeSeconds": [
      {
        "start": 63356,
        "end": 29718
      }
    ]

```
Shall we change this in the config README ?
-- Patrice.

**Comment by isalkind** [comment]
Greetings,
`activeTimes` is the global setting. `activeTimesForSensor` is the per-sensor setting. The README addresses the use of both of these parameters. Please note that your first config snippet shows `activeSeconds` which is not a valid configuration parameter.
Ian
