### ISSUE TITLE
Trigger names replaced by switch name

### ISSUE THREAD

**Issue by akagarwal** [isalkind/homebridge-away-mode#20]
During bridge setup, the switch name and trigger names show up correctly but after completing the setup in HomeKit, all trigger names get replaced by the switch name.

**Comment by isalkind** [comment]
This was raised in [Issue #16](https://github.com/isalkind/homebridge-away-mode/issues/16). I closed that one as an issue with HomeKit changes, but after some more exploring, there may be a way to address this. I will look into this further in the next couple of days.

cc: @brianleesmith

**Comment by isalkind** [comment]
I was able to dig into this further and follow the resolution used by another plugin developer (see: https://github.com/thoukydides/homebridge-homeconnect/issues/116). Adding the `ConfiguredName` characteristic to the motion sensors resolves the issue.

Fix is available in version `1.6.4`.
