### ISSUE TITLE
Unable to separate sensors by rooms

### ISSUE THREAD

**Issue by akagarwal** [isalkind/homebridge-away-mode#21]
All sensors are put in the same room. When creating automation, only the room name is shown in the automation UI and not the sensor name which requires an explicit automation name to be typed. It would be great to allow the in different rooms making it easier to create automations,

**Comment by isalkind** [comment]
Each instance of the Away Mode plugin is a single accessory. An accessory can only belong to a single room. If you want to put them into separate rooms, create multiple instances of the Away Mode plugin with only the sensors that you want in a room.
