### ISSUE TITLE
Reduce verbosity of logging by using Homebridge debug mode

### ISSUE THREAD

**Issue by PuzzledUser** [isalkind/homebridge-away-mode#24]
Homebridge logs (for other plugins) are obscured by lots of verbose logging from Away Mode. Relegate many log events to Homebridge Debug (-D) mode — they're still available when needed, but otherwise out of the way.

Replace initialisation dump of JSON timer config with summary of times for each sensor.

Also (perhaps controversially) add a new more compact single line log entry for ON events, rather than details of timers for future OFF (currently on) and ON (currently off) events. 

e.g. 
`[13/04/2023, 21:21:03] [Away Mode] Bed (0): Motion on for 1055s until [21:38:38]`

I've (hopefully) made a [Pull Request](https://github.com/isalkind/homebridge-away-mode/pull/25) with the specifics.
Cheers

**Comment by isalkind** [comment]
@PuzzledUser version 1.6.5 was published this morning that included your PR. Again, thanks for your efforts!
