### ISSUE TITLE
Enhancement 

### ISSUE THREAD

**Issue by jorgdeboer** [isalkind/homebridge-away-mode#4]
First of all, thanks for the perfect plugin and the updates, really appreciated!

I have one additional setting which might be usefull. Would it be possible to have a min/max on and off time per sensor? In some rooms (eg. hallway) I usually stay for 1-2minutes. Other rooms (eg. Living room) I stay for multiple hours. This would require different min/max on/off time per sensor right?

Thanks!

**Comment by isalkind** [comment]
I’m glad it works for you!

Let me think about your request. Seems like a reasonable thing to do. It could be done with multiple “away mode” accessories today, but it may be more elegant as you described.

**Comment by jorgdeboer** [comment]
Perfect, I’ll use your solution in the meantime.

**Comment by isalkind** [comment]
@jorgdeboer I just pushed a release that includes the enhancement you were looking for. You can now configure the min/max on and off times on a per-sensor basis. See the new '**sensors**' configuration parameter. Hope this works for you. Let me know if you have any questions.

**Comment by jorgdeboer** [comment]
Wow, very nice!

I’ll try it out tomorrow and definitely let you know. 

Thanks!

**Comment by jorgdeboer** [comment]
Couldn’t wait so I just tested it and seems to be working like a charm. Thanks!!

**Comment by isalkind** [comment]
Excellent. I'll close this issue now.
