### ISSUE TITLE
padStart is not a function error

### ISSUE THREAD

**Issue by johnnygoodface** [isalkind/homebridge-away-mode#5]
I'm using nodejs 6.17.1 on my Raspberry pi 3, and I get the error "**padStart is not a function**". 

As stated in this thread : https://github.com/EngageSoftware/DNN-JavaScript-Libraries/issues/45 the programmer removed the usage of that function so his program would remain v6 compatible. Could the same be done here? 

Otherwise I'm facing a nodejs update and I'm not really familliar (tried it but ran into these two errors: 

> /usr/lib/arm-linux-gnueabihf/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by the node)

 and 

> /usr/lib/arm-linux-gnueabihf/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by the node)

So if something could be done instead in the "homebridge-away-mode" that'd be great.

**Comment by isalkind** [comment]
@johnnygoodface I just published version 1.4.2 which should resolve your issue. Please give it a try.

**Comment by johnnygoodface** [comment]
Hello isalkind,
v1.4.2 now runs  without error and the new "AwayMode switch" is now showing in the Home app
I will configure some automations tomorrow around the 2 news triggers to test all out, but so far you nailed it! Thanks!

**Comment by johnnygoodface** [comment]
Hello isalkind,

I've already commented on github and I thank you :)

A quick note:
there's syntax error in the example at the bottom of the web page: a comma is missing before "location" and should read:

"activeTimes": [
            {
                "start": "sunset",
                "end": "22:00"
            }
        ],  <=========== missing
        "location": {

Cheers

Johnny

**Comment by isalkind** [comment]
Issue verified is fixed. Closing.
