### ISSUE TITLE
Random on/off multiple days

### ISSUE THREAD

**Issue by jorgdeboer** [isalkind/homebridge-away-mode#6]
Just out of interest, are the random times for on and off per sensor reset every day? Or are these random parameters the same for every day if the away mode is on for multiple consecutive days?

**Comment by isalkind** [comment]
On and off times are computed randomly every time they are needed. Sunrise and sunset times are computed daily. Hope that answers your question.

**Comment by jorgdeboer** [comment]
Yes definitely. Thanks
