### ISSUE TITLE
Consider adding a hard cutoff time to the Active Times

### ISSUE THREAD

**Issue by GitPuffy** [isalkind/homebridge-away-mode#7]
In this closed issue (https://github.com/isalkind/homebridge-away-mode/issues/2) you state the following:

> There are two ways sensors off. First, if you turn the "away mode" switch off, all sensors will immediately turn off. Second, if you use the 'startTime'/'endTime' parameters, an active (on) sensor will always complete its cycle (assuming "away mode" switch is still on) and then turn off, i.e., it won't turn off just because the 'endTime' has passed.

The flaw in this is that if I have a minimum on time for a light that triggers just before the end of the active time the forced minimum on time may run for a lengthy time after I do not want lights on any longer.  For example, in a child's bedroom I may have a setting that says to run the light for a minimum of 1.5 hours.  The end period may be at 9:30PM.  If your plugin triggers this light to turn on a minute before 9:30 it will then run until almost 11PM.  It would be nice if there was a setting that made the end period of the active time a hard setting of turning off that light at the end period time.

I understand that I could set an automation in Home App to turn off the "away" switch at 9:30PM but then away automation is now turned off and I would have to, daily, go into the Home App and turn on that "away" switch.  That may be inconvient if I was traveling.

What is your thought on this conundrum?  I find your plugin to be very valuable and adding a hard cut-off setting would make it perfect in my opinion.

Thank you.

**Comment by isalkind** [comment]
Glad you are finding the plugin useful. 

That sounds like a use case that is worth supporting. I’m in the middle of preparing a release. Let me see what it would take to add this behavior.

**Comment by isalkind** [comment]
@GitPuffy version 1.5.0 has been released to add hard cutoff support. Please give it a try.

**Comment by GitPuffy** [comment]
My first sets of tests indicate the "active period" settings are working as I hoped!  Thank you.
