### ISSUE TITLE
Keep switch state on restart

### ISSUE THREAD

**Issue by Daeny85** [isalkind/homebridge-away-mode#8]
When the Homebridge service is restarted the switch (Away Mode) loses its state. If you are not at home and the switch (Away Mode) is active it will be deactivated by restarting the Homebridge. So the presence simulation will not work anymore. 
The switch should save the state so that after the restart the state is the same as before the restart.

**Comment by isalkind** [comment]
Main switch (Away Mode) will save last known state and restart activity on restart if the switch was last active.

@Daeny85 Please take a look at version 1.5.1. This should address your issue.

**Comment by Daeny85** [comment]
Thank you. It works well.
